######################################################################
# Automatically generated by qmake (3.0) ven feb 1 18:56:53 2013
######################################################################

TEMPLATE = app
TARGET = qt-file
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
